const { join } = require('path')

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [join(__dirname, 'src/**/*.{js,ts,jsx,tsx,mdx}')],
  theme: {
    extend: {
      // Biz UI-aligned breakpoints
      screens: {
        sm: '320px',
        md: '672px',
        lg: '1056px',
        xlg: '1312px',
        max: '1584px',
      },
      colors: {
        /* Semantic colors */
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        primary: {
          DEFAULT: 'var(--primary)',
          foreground: 'var(--primary-foreground)',
          muted: 'var(--primary-muted)',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          foreground: 'var(--secondary-foreground)',
        },
        destructive: {
          DEFAULT: 'var(--destructive)',
          foreground: 'var(--destructive-foreground)',
          muted: 'var(--destructive-muted)',
        },
        success: {
          DEFAULT: 'var(--success)',
          foreground: 'var(--success-foreground)',
          muted: 'var(--success-muted)',
        },
        warning: {
          DEFAULT: 'var(--warning)',
          foreground: 'var(--warning-foreground)',
          muted: 'var(--warning-muted)',
        },
        info: {
          DEFAULT: 'var(--info)',
          foreground: 'var(--info-foreground)',
          muted: 'var(--info-muted)',
        },
        muted: {
          DEFAULT: 'var(--muted)',
          foreground: 'var(--muted-foreground)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
        },
        popover: {
          DEFAULT: 'var(--popover)',
          foreground: 'var(--popover-foreground)',
        },
        card: {
          DEFAULT: 'var(--card)',
          foreground: 'var(--card-foreground)',
        },



        /* Focus tokens */
        focus: 'var(--focus)',
        'focus-inset': 'var(--focus-inset)',

        /* Biz UI color palette */
        blue: {
          0: 'var(--biz-blue-0)',
          1: 'var(--biz-blue-1)',
          2: 'var(--biz-blue-2)',
          3: 'var(--biz-blue-3)',
          4: 'var(--biz-blue-4)',
          5: 'var(--biz-blue-5)',
          6: 'var(--biz-blue-6)',
          7: 'var(--biz-blue-7)',
          8: 'var(--biz-blue-8)',
          9: 'var(--biz-blue-9)',
          DEFAULT: 'var(--biz-blue-6)',
        },
        cyan: {
          0: 'var(--biz-cyan-0)',
          1: 'var(--biz-cyan-1)',
          2: 'var(--biz-cyan-2)',
          3: 'var(--biz-cyan-3)',
          4: 'var(--biz-cyan-4)',
          5: 'var(--biz-cyan-5)',
          6: 'var(--biz-cyan-6)',
          7: 'var(--biz-cyan-7)',
          8: 'var(--biz-cyan-8)',
          9: 'var(--biz-cyan-9)',
          DEFAULT: 'var(--biz-cyan-6)',
        },
        teal: {
          0: 'var(--biz-teal-0)',
          1: 'var(--biz-teal-1)',
          2: 'var(--biz-teal-2)',
          3: 'var(--biz-teal-3)',
          4: 'var(--biz-teal-4)',
          5: 'var(--biz-teal-5)',
          6: 'var(--biz-teal-6)',
          7: 'var(--biz-teal-7)',
          8: 'var(--biz-teal-8)',
          9: 'var(--biz-teal-9)',
          DEFAULT: 'var(--biz-teal-6)',
        },
        green: {
          0: 'var(--biz-green-0)',
          1: 'var(--biz-green-1)',
          2: 'var(--biz-green-2)',
          3: 'var(--biz-green-3)',
          4: 'var(--biz-green-4)',
          5: 'var(--biz-green-5)',
          6: 'var(--biz-green-6)',
          7: 'var(--biz-green-7)',
          8: 'var(--biz-green-8)',
          9: 'var(--biz-green-9)',
          DEFAULT: 'var(--biz-green-6)',
        },
        lime: {
          0: 'var(--biz-lime-0)',
          1: 'var(--biz-lime-1)',
          2: 'var(--biz-lime-2)',
          3: 'var(--biz-lime-3)',
          4: 'var(--biz-lime-4)',
          5: 'var(--biz-lime-5)',
          6: 'var(--biz-lime-6)',
          7: 'var(--biz-lime-7)',
          8: 'var(--biz-lime-8)',
          9: 'var(--biz-lime-9)',
          DEFAULT: 'var(--biz-lime-6)',
        },
        yellow: {
          0: 'var(--biz-yellow-0)',
          1: 'var(--biz-yellow-1)',
          2: 'var(--biz-yellow-2)',
          3: 'var(--biz-yellow-3)',
          4: 'var(--biz-yellow-4)',
          5: 'var(--biz-yellow-5)',
          6: 'var(--biz-yellow-6)',
          7: 'var(--biz-yellow-7)',
          8: 'var(--biz-yellow-8)',
          9: 'var(--biz-yellow-9)',
          DEFAULT: 'var(--biz-yellow-6)',
        },
        orange: {
          0: 'var(--biz-orange-0)',
          1: 'var(--biz-orange-1)',
          2: 'var(--biz-orange-2)',
          3: 'var(--biz-orange-3)',
          4: 'var(--biz-orange-4)',
          5: 'var(--biz-orange-5)',
          6: 'var(--biz-orange-6)',
          7: 'var(--biz-orange-7)',
          8: 'var(--biz-orange-8)',
          9: 'var(--biz-orange-9)',
          DEFAULT: 'var(--biz-orange-6)',
        },
        pink: {
          0: 'var(--biz-pink-0)',
          1: 'var(--biz-pink-1)',
          2: 'var(--biz-pink-2)',
          3: 'var(--biz-pink-3)',
          4: 'var(--biz-pink-4)',
          5: 'var(--biz-pink-5)',
          6: 'var(--biz-pink-6)',
          7: 'var(--biz-pink-7)',
          8: 'var(--biz-pink-8)',
          9: 'var(--biz-pink-9)',
          DEFAULT: 'var(--biz-pink-6)',
        },
        violet: {
          0: 'var(--biz-violet-0)',
          1: 'var(--biz-violet-1)',
          2: 'var(--biz-violet-2)',
          3: 'var(--biz-violet-3)',
          4: 'var(--biz-violet-4)',
          5: 'var(--biz-violet-5)',
          6: 'var(--biz-violet-6)',
          7: 'var(--biz-violet-7)',
          8: 'var(--biz-violet-8)',
          9: 'var(--biz-violet-9)',
          DEFAULT: 'var(--biz-violet-6)',
        },
        indigo: {
          0: 'var(--biz-indigo-0)',
          1: 'var(--biz-indigo-1)',
          2: 'var(--biz-indigo-2)',
          3: 'var(--biz-indigo-3)',
          4: 'var(--biz-indigo-4)',
          5: 'var(--biz-indigo-5)',
          6: 'var(--biz-indigo-6)',
          7: 'var(--biz-indigo-7)',
          8: 'var(--biz-indigo-8)',
          9: 'var(--biz-indigo-9)',
          DEFAULT: 'var(--biz-indigo-6)',
        },
        grape: {
          0: 'var(--biz-grape-0)',
          1: 'var(--biz-grape-1)',
          2: 'var(--biz-grape-2)',
          3: 'var(--biz-grape-3)',
          4: 'var(--biz-grape-4)',
          5: 'var(--biz-grape-5)',
          6: 'var(--biz-grape-6)',
          7: 'var(--biz-grape-7)',
          8: 'var(--biz-grape-8)',
          9: 'var(--biz-grape-9)',
          DEFAULT: 'var(--biz-grape-6)',
        },
        red: {
          0: 'var(--biz-red-0)',
          1: 'var(--biz-red-1)',
          2: 'var(--biz-red-2)',
          3: 'var(--biz-red-3)',
          4: 'var(--biz-red-4)',
          5: 'var(--biz-red-5)',
          6: 'var(--biz-red-6)',
          7: 'var(--biz-red-7)',
          8: 'var(--biz-red-8)',
          9: 'var(--biz-red-9)',
          DEFAULT: 'var(--biz-red-6)',
        },
        gray: {
          0: 'var(--biz-gray-0)',
          1: 'var(--biz-gray-1)',
          2: 'var(--biz-gray-2)',
          3: 'var(--biz-gray-3)',
          4: 'var(--biz-gray-4)',
          5: 'var(--biz-gray-5)',
          6: 'var(--biz-gray-6)',
          7: 'var(--biz-gray-7)',
          8: 'var(--biz-gray-8)',
          9: 'var(--biz-gray-9)',
          DEFAULT: 'var(--biz-gray-6)',
        },
        dark: {
          0: 'var(--biz-dark-0)',
          1: 'var(--biz-dark-1)',
          2: 'var(--biz-dark-2)',
          3: 'var(--biz-dark-3)',
          4: 'var(--biz-dark-4)',
          5: 'var(--biz-dark-5)',
          6: 'var(--biz-dark-6)',
          7: 'var(--biz-dark-7)',
          8: 'var(--biz-dark-8)',
          9: 'var(--biz-dark-9)',
          DEFAULT: 'var(--biz-dark-6)',
        },
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: 'var(--radius-full)',
      },
      fontFamily: {
        sans: [
          'IBM Plex Sans',
          'Inter',
          'Open Sans',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'Arial',
          'sans-serif',
        ],
        mono: [
          'IBM Plex Mono',
          'ui-monospace',
          'SFMono-Regular',
          'SF Mono',
          'Menlo',
          'Monaco',
          'Consolas',
          'Liberation Mono',
          'Courier New',
          'monospace',
        ],
      },
      zIndex: {
        dropdown: 'var(--z-dropdown)',
        sticky: 'var(--z-sticky)',
        modal: 'var(--z-modal)',
        popover: 'var(--z-popover)',
        tooltip: 'var(--z-tooltip)',
      },
      transitionDuration: {
        fast: 'var(--transition-fast)',
        base: 'var(--transition-base)',
        slow: 'var(--transition-slow)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
      },
      animation: {
        'accordion-down': 'biz-accordion-down 0.2s ease-out',
        'accordion-up': 'biz-accordion-up 0.2s ease-out',
      },
      gridColumn: {
        'span-13': 'span 13 / span 13',
        'span-14': 'span 14 / span 14',
        'span-15': 'span 15 / span 15',
        'span-16': 'span 16 / span 16',
        'span-17': 'span 17 / span 17',
        'span-18': 'span 18 / span 18',
        'span-19': 'span 19 / span 19',
        'span-20': 'span 20 / span 20',
        'span-21': 'span 21 / span 21',
        'span-22': 'span 22 / span 22',
        'span-23': 'span 23 / span 23',
        'span-24': 'span 24 / span 24',
      },
      spacing: {
        'ocean-col-sm-1': '8.333333%',
        'ocean-col-sm-2': '16.666667%',
        'ocean-col-sm-3': '25%',
        'ocean-col-sm-4': '33.333333%',
        'ocean-col-sm-5': '41.666667%',
        'ocean-col-sm-6': '50%',
        'ocean-col-sm-7': '58.333333%',
        'ocean-col-sm-8': '66.666667%',
        'ocean-col-sm-9': '75%',
        'ocean-col-sm-10': '83.333333%',
        'ocean-col-sm-11': '91.666667%',
        'ocean-col-sm-12': '100%',
        'ocean-col-md-1': '8.333333%',
        'ocean-col-md-2': '16.666667%',
        'ocean-col-md-3': '25%',
        'ocean-col-md-4': '33.333333%',
        'ocean-col-md-5': '41.666667%',
        'ocean-col-md-6': '50%',
        'ocean-col-md-7': '58.333333%',
        'ocean-col-md-8': '66.666667%',
        'ocean-col-md-9': '75%',
        'ocean-col-md-10': '83.333333%',
        'ocean-col-md-11': '91.666667%',
        'ocean-col-md-12': '100%',
        'ocean-col-lg-1': '8.333333%',
        'ocean-col-lg-2': '16.666667%',
        'ocean-col-lg-3': '25%',
        'ocean-col-lg-4': '33.333333%',
        'ocean-col-lg-5': '41.666667%',
        'ocean-col-lg-6': '50%',
        'ocean-col-lg-7': '58.333333%',
        'ocean-col-lg-8': '66.666667%',
        'ocean-col-lg-9': '75%',
        'ocean-col-lg-10': '83.333333%',
        'ocean-col-lg-11': '91.666667%',
        'ocean-col-lg-12': '100%',
        'ocean-col-xlg-1': '8.333333%',
        'ocean-col-xlg-2': '16.666667%',
        'ocean-col-xlg-3': '25%',
        'ocean-col-xlg-4': '33.333333%',
        'ocean-col-xlg-5': '41.666667%',
        'ocean-col-xlg-6': '50%',
        'ocean-col-xlg-7': '58.333333%',
        'ocean-col-xlg-8': '66.666667%',
        'ocean-col-xlg-9': '75%',
        'ocean-col-xlg-10': '83.333333%',
        'ocean-col-xlg-11': '91.666667%',
        'ocean-col-xlg-12': '100%',
        'ocean-col-max-1': '8.333333%',
        'ocean-col-max-2': '16.666667%',
        'ocean-col-max-3': '25%',
        'ocean-col-max-4': '33.333333%',
        'ocean-col-max-5': '41.666667%',
        'ocean-col-max-6': '50%',
        'ocean-col-max-7': '58.333333%',
        'ocean-col-max-8': '66.666667%',
        'ocean-col-max-9': '75%',
        'ocean-col-max-10': '83.333333%',
        'ocean-col-max-11': '91.666667%',
        'ocean-col-max-12': '100%',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
